[web]
web-server ansible_host=3.96.127.95

[app]
app-server ansible_host=16.52.169.142

[db]
db-server ansible_host=15.222.1.156

[all:vars]
ansible_user=ec2-user
ansible_ssh_private_key_file=~/.ssh/terra-server-key.pem

[application:children]
web
app

[all_servers:children]
application
db

