name: Day 44 - Secrets

on:
  workflow_dispatch:

jobs:
  secrets-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Check if secret is set
        run: |
          if [ -n "$MY_SECRET_MESSAGE" ]; then
            echo "The secret is set: true"
          else
            echo "The secret is set: false"
          fi
        env:
          MY_SECRET_MESSAGE: ${{ secrets.MY_SECRET_MESSAGE }}

      - name: Try printing secret directly
        run: |
          echo "Secret value is ${{ secrets.MY_SECRET_MESSAGE }}"
