name: Day 44 - Real Tests

on:
  push:
    branches:
      - DevOps-practice

  workflow_dispatch:

jobs:
  run-real-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run test script
        run: python scripts/check_day_44.py
