name: Self-Hosted Job

on: push

jobs:
  run-on-my-machine:
    runs-on: self-hosted
    steps:
  
      - name: Create a test file
        run: echo "Hello from GitHub Actions" > day42-test.txt

      - name: Show the file was created
        run: cat day42-test.txt
